import { toAbsoluteUrl } from "@/lib/site"

export async function GET() {
  const lines = [
    "# robots.txt for Estalara",
    "",
    "User-agent: GPTBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: CCBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: Googlebot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: Bingbot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    "User-agent: *",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "",
    `Sitemap: ${toAbsoluteUrl("/sitemap.xml")}`,
    `# llms.txt: ${toAbsoluteUrl("/llms.txt")}`,
    "",
  ].join("\n")

  return new Response(lines, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  })
}
